### ISSUE TITLE
ヘッダーのデザインを統一する

### ISSUE THREAD

**Issue by ry-na** [ry-na/cchan#30]
現在、トップページとスレでヘッダーのデザインが微妙に違うので、どちらかに統一をお願いします。
<img width="190" alt="Screen Shot 2019-11-30 at 17 00 31" src="https://user-images.githubusercontent.com/21969328/69895376-0f895480-1393-11ea-9689-07566f86c871.png">
<img width="171" alt="Screen Shot 2019-11-30 at 17 00 36" src="https://user-images.githubusercontent.com/21969328/69895377-10ba8180-1393-11ea-941e-e8e1d38e36b4.png">

**Comment by suzukitomofumi** [comment]
6f925e7
